rosdistro: 'melodic

  '
roslaunch:
  uris: {host_ursa_major__34583: 'http://ursa-major:34583/'}
rosversion: '1.14.3

  '
run_id: 88fe3de8-504d-11ea-a591-00044bddba3d

bus:
  device: can0 # socketcan network
  loopback: false # socket should loop back messages
  driver_plugin: can::SocketCANInterface
  master_allocator: canopen::SimpleMaster::Allocator
sync:
  interval_ms: 100 # set to 0 to disable sync
  update_ms: <interval_ms> #update interval of control loop, must be set explecitly if sync is disabled
  overflow: 0 # overflow sync counter at value or do not set it (0, default)
heartbeat: # simple heartbeat producer, optional!
  rate: 2000 # heartbeat rate
  msg: "701#05" # message to send, cansend format: heartbeat of node 1 with status 5=Started
nodes:
  node2:
    id: 2
    name: propulsion
    eds_pkg: little_pig_ctrl
    eds_file: "/config/HBL2360A.eds"
    publish: ["0x210Dsub0!"] #,"0x1017sub00","0x1000sub00"]
