sync:
  interval_ms: 500   #made longer for testing
  overflow: 10
heartbeat:
  rate: 1
  msg: "77f#05"

nodes:

  RoboTeq_HBL2360A:
    eds_pkg: little_pig_ctrl
    eds_file: "/config/HBL2360A.eds"
    id: 8

    joint: right_steering_joint
    motor_allocator: canopen::Motor402_2::Allocator
    pos_to_device: "(pos * 8196) / (2 * pi)"
    pos_from_device:  "(obj6064 * 2 * pi) / 8196"
    #position is rad * 1/(2*pi) rev/rad * 8196 p/mrev * 47 srev/mrev  #this goes radians -> pulses, NOTE: gearbox reduces by 47
    motor_layer:
      switching_state: 5 #operation enable

    joint_2: right_front_axle
    motor_allocator_2: canopen::Motor402_1::Allocator
    vel_to_device_2: "(vel * 60) / (12 * (2 * pi) * 0.0254)"
    vel_from_device: "(obj606C * (12 * 2 * pi) * 0.0254) / 60"
    #velocity is m/s * 60 s/min * 1/0.0254 in/m * 1 / (2*pi*12) rev/in  #this goes m/s -> rev/min
    motor_layer_2:
      switching_state: 5 #operation enable

    #publish:
      #- "0x210Dsub2!" #	Battery Volts
      #- "0x210Fsub2!" #	Temp 1
      #- "0x210Fsub3!" #	Temp 2
      #- "0x6041!" #		Status Word 1
      #- "0x6841!" #		Status Word 2
      #- "0x210Asub1!" #	Motor 1 Speed
      #- "0x2122sub1!" #	Motor 1 Status Flag
      #- "0x2100sub1!" #	Motor 1 Amps
      #- "0x2104sub2!" #	Motor 2 Encoder Count
      #- "0x2122sub2!" #	Motor 2 Status Flag
      #- "0x2100sub2!" #	Motor 2 Amps
      #- "0x2112!" #		Fault Flag


#defaults:
  #dcf_overlay: these can be manually set
    #"6083": "1000000" # profile acceleration
    #"6084": "1000000" # profile deceleration
    #"60C5": "1000000" # maximum acceleration
    #"60C6": "1000000" # maximum deceleration
    #"6099sub1": "100000" # find switch (coarse)
    #"6099sub2": "10000" # find home (fine)
    #"1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
    #  "6098": "35" # homing method
    #vel_from_device: #"p1 != p1 || obj2041 == t1 ? 0 : deg2rad(1000*norm(obj6064-p1,-36000000,36000000)/norm(obj2041-t1,0,2^32)), p1=p0, p0 = obj6064, t1 = t0, t0 = obj2041"
    #eff_from_device: #"obj6078/1000.0*14.14" #CL[1]=14.14