## control_mode_adapter
# max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

steering_controller:
  joint: right_steering_joint
  required_drive_mode: 1 #profile position
  type: position_controllers/JointPositionController
  #pid: {p: 0.0, i: 0.0, d: 0.0}

propulsion_controller:
  joint: right_front_axle
  #required_drive_mode: -4 #Velocity Position
  required_drive_mode: 2 #Velocity
  type: velocity_controllers/JointVelocityController
  #pid: {p: 0.0, i: 0.0, d: 0.0}