## joint_names
#joint_names: [right_front_axle]

## control_mode_adapter
# max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

## velocity_controller
#velocity_controller:
  #joint: right_front_axle
  #type: velocity_controllers/JointVelocityController
  ## pid: {p: 3.0, i: 0.0, d: 0.0} was not used in torse_controller
  #required_drive_mode: 3 #profile velocity
  ## max_rot_velocity: 1.0
  ## max_trans_velocity: 1.0

left_steering_ctrlr:
  joint: left_steering_joint
  type: position_controllers/JointPositionController
  pid: {p: 1000.0, i: 0.0, d: 1.0}
right_steering_ctrlr:
  joint: right_steering_joint
  required_drive_mode: 1 #profile position
  type: position_controllers/JointPositionController
  pid: {p: 1000.0, i: 0.0, d: 1.0}

left_front_axle_ctrlr:
  joint: left_front_axle
  type: velocity_controllers/JointVelocityController
  pid: {p: 100.5, i: 1.0, d: 0.0, i_clamp: 10.0}
right_front_axle_ctrlr: #This is where I had velocity controller
  joint: right_front_axle
  #The old controller was an velocity_controllers/JointVelocityController
  required_drive_mode: 3 #profile velocity
  type: velocity_controllers/JointVelocityController
  pid: {p: 100.5, i: 1.0, d: 0.0, i_clamp: 10.0}
left_rear_axle_ctrlr:
  joint: left_rear_axle
  type: velocity_controllers/JointVelocityController
  pid: {p: 100.5, i: 1.0, d: 0.0, i_clamp: 10.0}
right_rear_axle_ctrlr:
  joint: right_rear_axle
  type: velocity_controllers/JointVelocityController
  pid: {p: 100.5, i: 1.0, d: 0.0, i_clamp: 10.0}
    
  
