# # Left steering link
# left_steering_postion_ctrl:
#   type: effort_controllers/JointPositionController
#   joint: base_link_left_ackerman_link
#   # These PIDs might need to be adjusted
#   pid: { p: 1000.0, i: 0.01, d: 10.0 }

# # Right steering link
# right_steering_postion_ctrl:
#   type: effort_controllers/JointPositionController
#   joint: base_link_right_ackerman_link
#   # These PIDs might need to be adjusted
#   pid: { p: 1000.0, i: 0.01, d: 10.0 }

# # Axle velocity controllers

# # Front left wheel
# front_left_wheel_velocity_ctrl:
#   type: effort_controllers/JointPositionController
#   joint: left_ackerman_link_front_left_wheel
#   # These PIDs might need to be adjusted
#   pid: { p: 10000.0, i: 0.01, d: 10.0 }

# # Front right wheel
# front_right_wheel_velocity_ctrl:
#   type: effort_controllers/JointPositionController
#   joint: right_ackerman_link_front_right_wheel
#   # These PIDs might need to be adjusted
#   pid: { p: 10000.0, i: 0.01, d: 10.0 }

# # Rear left wheel
# rear_left_wheel_velocity_ctrl:
#   type: effort_controllers/JointPositionController
#   joint: base_link_rear_left_wheel
#   # These PIDs might need to be adjusted
#   pid: { p: 10000.0, i: 0.01, d: 10.0 }

# # Rear right wheel
# rear_right_wheel_velocity_ctrl:
#   type: effort_controllers/JointPositionController
#   joint: base_link_rear_right_wheel
#   # These PIDs might need to be adjusted
#   pid: { p: 10000.0, i: 0.01, d: 10.0 }


# front_left_wheel:
#   steering_link_name: left_ackerman_link
#   steering_controller_name: left_steering_position_ctrl
#   axle_controller_name: front_left_wheel_velocity_ctrl
#   diameter: 0.605

# front_right_wheel:
#   steering_link_name: right_ackerman_link
#   steering_controller_name: right_steering_position_ctrl
#   axle_controller_name: front_right_wheel_velocity_ctrl
#   diameter: 0.605

# rear_left_wheel:
#   link_name: left_rear_wheel
#   axle_controller_name: rear_left_wheel_velocity_ctrl
#   diameter: 0.635

# rear_right_wheel:
#   link_name: right_rear_wheel
#   axle_controller_name: rear_right_wheel_velocity_ctrl
#   diameter: 0.635